# Generated by Django 2.2.5 on 2020-10-21 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('restaurant', models.TextField(null=True)),
                ('review', models.TextField(null=True)),
            ],
        ),
    ]
